# NUMPY

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [5]:
# create a numpy array 
# creating a 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# how to find the type of array 
print(type(arr1))

# how to find a shape of array
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# reshape the array to 2D
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5)  # reshape to 1 row and 5 coluumns


array([[1, 2, 3, 4, 5]])

In [ ]:
# list of lists
# creating a 2D array
arr3 = np.array([[1, 2, 3, 4, 5]])
arr3.shape  # shape of 2D array

(1, 5)

In [ ]:
# 2D array with multiple rows
# creating a 2D array with 2 rows and 5 columns
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  # creating a 2D array with 2 rows and 5 columns
print(arr4)
arr4.shape  

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [21]:
# create a arraay with inbuilt function

np.arange(1, 11, 2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
# create a 3x3 array of ones
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])
# Displaying the properties of the array
print("Array: \n", arr)
print("Shape of the array;", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type oh the array:", arr.dtype)
print("Size of the arraay:", arr.size)

[[1 2 3]
 [4 5 6]]
Array: 
 [[1 2 3]
 [4 5 6]]
Shape of the array; (2, 3)
Number of dimensions: 2
Data type oh the array: int64
Size of the arraay: 6


In [30]:
# Numpy Vectorized Operations 

ver_arr = np.array([1,2,3,4,5])
ver1_arr = np.array([6,7,8,9,10])

# Adding two arrays
print("The Addition of the two arrays:", ver_arr + ver1_arr)

# Subtracting two arrays
print("The Subtraction of the two arrays:", ver1_arr - ver_arr)     

# Multiplying two arrays
print("The Multiplication of the two arrays:", ver_arr * ver1_arr)

# Dividing two arrays
print("The Division of the two arrays:", ver1_arr / ver_arr)

The Addition of the two arrays: [ 7  9 11 13 15]
The Subtraction of the two arrays: [5 5 5 5 5]
The Multiplication of the two arrays: [ 6 14 24 36 50]
The Division of the two arrays: [6.         3.5        2.66666667 2.25       2.        ]


In [ ]:
# Universal Functions in Numpy
arr = np.array([1,2,3,4,5])
# Square root of an array
print("Square root of the array:", np.sqrt(arr))
# Exponential of an array
print("Exponential of the array:", np.exp(arr))
# Logarithm of an array
print("Logarithm of the array:", np.log(arr))
# Trigonometric functions
print("Sine of the array:", np.sin(arr))
print("Cosine of the array:", np.cos(arr))
# Linear Algebra Operations
# Dot product of two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Dot product of the two arrays:\n", np.dot(arr1, arr2))   
   

Square root of the array: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of the array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm of the array: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine of the array: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine of the array: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Dot product of the two arrays:
 [[19 22]
 [43 50]]


In [40]:
# Array Slicing and Indexing
# Creating a 2D array

arry = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: \n",arry)


Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
# Slicing the first element of the first row
arry[0, 0]

np.int64(1)

In [ ]:
arry[1:] # Slicing the second row and second column onwards

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
arry[1:, 1:]  # Slicing the second row and second column onwards

array([[5, 6],
       [8, 9]])

In [ ]:
arry[2: , 1:] 

array([[8, 9]])

In [52]:
# Modify the elements
arry[0,1]= 10  # Modifying the first row and second column element
print("Modified Array: \n", arry)

Modified Array: 
 [[ 1 10  3]
 [ 4  5  6]
 [ 7  8  9]]


In [58]:
# statical methods
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Mean 
mean = np.mean(data)
print("Mean of the data:", mean)

# Median
median = np.median(data)
print("Median of the data:", median)

# Standard Deviation
std_div = np.std(data)
print("Standard Deviation of the data:", std_div)

# variance 
variance = np.var(data)
print("Variance of the data:", variance)

Mean of the data: 5.0
Median of the data: 5.0
Standard Deviation of the data: 2.581988897471611
Variance of the data: 6.666666666666667


In [ ]:
# Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
data>5 # Logical operation to check if the elements are greater than 5

# 
data[data >= 5]  # Displaying the elements greater than 5

array([ 6,  7,  8,  9, 10])

In [61]:
data[(data < 5) & (data > 2)]  # Displaying the elements less than 5 and greater than 2

array([3, 4])