# Assignment1: Array Creation and Manipulation

# Q1

In [ ]:
import numpy as np

array = np.random.randint(1, 21, size=(5, 5))  # Creating a 5x5 array with random integers between 1 and 20
print("Original Array:")
print(array)

Original Array:
[[ 9  6  9 20 13]
 [17 16 19 17 10]
 [ 4 20  6  8  1]
 [ 1 19 12 19  5]
 [15 13 10  9 17]]


In [ ]:
# replace all the elements in the third column with 1
array[:, 2]=1 # Replacing all elements in the third column with 1
print("Modified array:")
print(array)


Modified array:
[[ 9  6  1 20 13]
 [17 16  1 17 10]
 [ 4 20  1  8  1]
 [ 1 19  1 19  5]
 [15 13  1  9 17]]


# Q2

In [4]:
import numpy as np

In [8]:
array = np.arange(1,17).reshape((4,4))
print("Original Array:")
print(array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
# replace the diagonal elements with 0
np.fill_diagonal(array, 0)
print("Modified Array:")
print(array)

Modified Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
