# Assignment10: Masked Arrays 

# Q1

In [6]:
import numpy as np
import numpy.ma as ma


In [8]:
# create a masked array of shape (4,4) with random integers
array = np.random.randint(1,21, size=(4,4))
masked_array = ma.masked_greater(array, 10)
print(f"Original Array:\n{array}")
print("Masked Array:")
print(masked_array)

Original Array:
[[18 18  1  4]
 [14  2  2 20]
 [ 4  8  3 18]
 [18  8 19 20]]
Masked Array:
[[-- -- 1 4]
 [-- 2 2 --]
 [4 8 3 --]
 [-- 8 -- --]]


In [10]:
# compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print(f"Sum of unmasked elements:{sum_unmasked}")

Sum of unmasked elements:32


# Q2

In [13]:
# create a masked array of shape (3,3) with random integers and mask the diagonal elements
array = np.random.randint(1,10, size=(3,3))
masked_dia_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original Array:")
print(array)
print("Masked Array:")
print(masked_dia_array)



Original Array:
[[2 2 1]
 [5 1 7]
 [9 6 8]]
Masked Array:
[[-- 2 1]
 [5 -- 7]
 [9 6 --]]


In [14]:
# Replace a masked elements with the mean of the unmasked elements
mean_masked = masked_array.mean()
masked_array = masked_array.filled(mean_masked)
print("Mean Masked:")
print(mean_masked)
print("Masked Array:")
print(masked_array)

Mean Masked:
6.166666666666667
Masked Array:
[[6 9 5]
 [1 6 6]
 [9 7 6]]
