# Assignnment2: Array Indexing and Slicing 

# Q1


In [ ]:
import numpy as np

In [ ]:
# Create a numpy array of sha[e (6, 6) with values from 1 to 36]
array = np.arange(1,37).reshape((6,6))
print("Original Array:")
print(array)


Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [4]:
# Extract the sub-array
sub_array = array[2:5, 1:4]
print("Original Array:")
print(sub_array)

Original Array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


# Q2

In [6]:
# Create a numpy array of shape (5,5) with random integers
array = np.random.randint(1, 100, size=(5,5))
print("Original Array:")
print(array)


Original Array:
[[55 37 47 40 65]
 [ 7 66 42 89 46]
 [69 21 92 15 67]
 [41 33  8 80 84]
 [52 82 40 83 81]]


In [7]:
# Extract the elements on the brorder of the array
border_elements = np.concatenate((array[0, :], array[-1,:], array[1:-1, 0], array[1:-1, -1] ))
print("Border Elements:")
print(border_elements)

Border Elements:
[55 37 47 40 65 52 82 40 83 81  7 69 41 46 67 84]


array[0, :] selects all elements in the first row.

array[-1, :] selects all elements in the last row.

array[1:-1, 0] selects the first element of each row except the first and last rows (the left border).

array[1:-1, -1] selects the last element of each row except the first and last rows (the right border).