# Assignment3: Array Operations

# Q1

In [6]:
import numpy as np

In [7]:
# Create two numpy arrays of shape (3, 4) with random integers from 1 to 10
array1 = np.random.randint(1, 11, size=(3,4))
array2 = np.random.randint(1, 11, size=(3,4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

Array 1:
[[ 1 10  9  4]
 [ 8  1  3  4]
 [ 7  4  6  5]]
Array 2:
[[ 6  9 10  7]
 [10 10  3  6]
 [ 1  6  8 10]]


In [8]:
# Perform element wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Addition:")
print(addition)
print("Subtraction:")
print(subtraction)
print("Multiplication:")
print(multiplication)
print("Division:")
print(division)

Addition:
[[ 7 19 19 11]
 [18 11  6 10]
 [ 8 10 14 15]]
Subtraction:
[[-5  1 -1 -3]
 [-2 -9  0 -2]
 [ 6 -2 -2 -5]]
Multiplication:
[[ 6 90 90 28]
 [80 10  9 24]
 [ 7 24 48 50]]
Division:
[[0.16666667 1.11111111 0.9        0.57142857]
 [0.8        0.1        1.         0.66666667]
 [7.         0.66666667 0.75       0.5       ]]


# Q2

In [10]:
# cretae a numpy array of shape (4,4) with values from 1 to 16
array = np.arange(1,17).reshape((4,4))
print("Array from 1 to 16:")
print(array)

Array from 1 to 16:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# compute the row-wise and column-wise sums
row_sums = np.sum(array, axis=1) # Row-wise sums
column_sums = np.sum(array, axis=0) # Column-wise sums
print("Row-wise sums:")
print(row_sums)
print("Column-wise sums:")
print(column_sums)

Row-wise sums:
[10 26 42 58]
Column-wise sums:
[28 32 36 40]
