# Assignment4: Statistical Operations

# Q1

In [2]:
import numpy as np

In [3]:
# create a numpy array of shape (5,5) filled with random integers
array = np.random.randint(1,21, size=(5,5))
print("Original Array: ")
print(array)

Original Array: 
[[ 2  8 13 14 16]
 [14  1  1 16 20]
 [18  6 13 19 14]
 [18  5  5 10  5]
 [18 11 10  5 11]]


In [7]:
# compute the mean, median, standard deviation and variance of the array
mean = np.mean(array)
median = np.median(array)
stnd_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:",median)
print("Standard Deviation:", stnd_dev)
print("Variance:", variance)

Mean: 10.92
Median: 11.0
Standard Deviation: 5.789093193238472
Variance: 33.513600000000004


# Q2

In [8]:
# create a numpy array of shape (3, 3) with value from 1 to 9
array = np.arange(1,10).reshape(3, 3)
print("Original Array:")
print(array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalize = (array-mean) / std_dev
print("Normalize array")
print(normalize)

Normalize array
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
