# Assignment5: Boardcasting

# Q1

In [2]:
import numpy as np

In [5]:
# create a numpy array of shape (3,3) fille with random intergers
array = np.random.randint(1,11, size=(3,3))
row_array = np.random.randint(1,11, size=(3,))
print(f"Original Array:\n {array}")
print(f"1d array: \n {row_array}")

Original Array:
 [[ 7  8  7]
 [ 9  3  9]
 [10  1  7]]
1d array: 
 [10  5  5]


In [6]:
# add 1 d aray of shape(3,) to each row of the 2d array using boardcasting
result = array + row_array
print(f"Resulting array: \n {result}")

Resulting array: 
 [[17 13 12]
 [19  8 14]
 [20  6 12]]


# Q2

In [7]:
# create a numpy array of shape (4,4) filled with random integers
array = np.random.randint(1,20, size=(4,4))
colunm_array = np.random.randint(1,20, size=(4,))
print(f"Original Array:\n {array}")
print(f"Colunm Array:\n {colunm_array}")


Original Array:
 [[ 7 19 17  2]
 [ 6 15 13  7]
 [10 18  4  9]
 [17 12 10 10]]
Colunm Array:
 [ 6 19 18  2]


In [8]:
# Subtract a 1d array of shape (4,) from each colunm of the 2d array using broadcasting
result = array - colunm_array
print(f"Resulting:\n {result}")




Resulting:
 [[  1   0  -1   0]
 [  0  -4  -5   5]
 [  4  -1 -14   7]
 [ 11  -7  -8   8]]
