# Assignment6: Linear Algebra

# Q1

In [2]:
import numpy as np

In [3]:
# create a numpy array of shape(3,3) represent a matrix
matrix = np.random.randint(1,11 , size=(3,3))
print(f"Original Matrix Array:\n {matrix}")

Original Matrix Array:
 [[ 4  7  8]
 [ 9  6  6]
 [ 1  6 10]]


In [4]:
# compute its determinant
determinant = np.linalg.det(matrix)
print(f"Determinant:\n{determinant}")

Determinant:
-108.00000000000003


In [5]:
# compute its inverse 
inverse = np.linalg.inv(matrix)
print(f"Inverse:\n{inverse}")

Inverse:
[[-0.22222222  0.2037037   0.05555556]
 [ 0.77777778 -0.2962963  -0.44444444]
 [-0.44444444  0.15740741  0.36111111]]


In [ ]:
# compute its eigenvalues
eng = np.linalg.eigvals(matrix) 
print(f"Eigenvalues:\n{eng}")

Eigenvalues:
[-1.8673861   3.07807144 18.78931466]


# Q2

In [8]:
# create a two numpy arrays of shape(2,3) and (3,2)
array1 = np.random.randint(1,20 , size=(2,3))
array2 = np.random.randint(1,20, size=(3,2))
print(f"Original Array1:\n{array1} ")
print(f"Original Array2:\n{array2} ")


Original Array1:
[[12  5  6]
 [17 12 18]] 
Original Array2:
[[ 1 16]
 [ 2 14]
 [ 9 11]] 


In [10]:
# perform matrix multiplication on these arrays
mul = np.dot(array1 , array2)
print(f"Multiplication of two Array is:\n{mul} ")


Multiplication of two Array is:
[[ 76 328]
 [203 638]] 
