# Assignment7: Advanced Array Manipulation

# Q1

In [1]:
import numpy as np

In [2]:
# create a umpy array of shape (3,3) with values from 1 to 9
array = np.arange(1,10).reshape((3,3))
print(f"Original Array:\n{array}")

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Reshape the array to shape (1,9)
reshaped_array1 = array.reshape((1,9))
print(f"Reshaped Array1:\n{reshaped_array1} ")


Reshaped Array1:
[[1 2 3 4 5 6 7 8 9]] 


In [5]:
# Reshape the array to shape (9,1)
reshaped_array2 = array.reshape((9,1))
print(f"Reshaped Array2:\n{reshaped_array2} ")

Reshaped Array2:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] 


# Q2

In [6]:
# Create a numpy array of shape (5,5) filles with random intergers
array = np.random.randint(1,26, size=(5,5))
print(f"Original Array:\n {array}")


Original Array:
 [[ 5 19  8 23 10]
 [23 12 23  6 13]
 [ 2  6 19  7 18]
 [20  8  6 19 11]
 [15  1 18 23 20]]


In [7]:
# Flatten the array
flattened_array = array.flatten()
print(f"Flattened Array:\n{flattened_array}")

Flattened Array:
[ 5 19  8 23 10 23 12 23  6 13  2  6 19  7 18 20  8  6 19 11 15  1 18 23
 20]


In [8]:
# Reshape the array back to (5,5)
reshaped_array = flattened_array.reshape((5,5))
print(f"Reshaped Array:\n{reshaped_array}")

Reshaped Array:
[[ 5 19  8 23 10]
 [23 12 23  6 13]
 [ 2  6 19  7 18]
 [20  8  6 19 11]
 [15  1 18 23 20]]
