# Assignment8: Fancy Indexing and Boolean Indexing


# Q1

In [2]:
import numpy as np

In [3]:
# create a nummpy array of shape (5,5) filled with random integers
array = np.random.randint(1, 21, size=(5,5))
print(f"Original Array:\n {array}")

Original Array:
 [[12  2  7  2 10]
 [12  5 13 15 13]
 [18  2  6 20  7]
 [17 15  5 17 10]
 [16 11 16 13  9]]


These four corner values are then stored in a new one-dimensional array called corners.

In [4]:
# use fancy indexing to extract the elements at the corners of the array
#  top-left, top-right, bottom-left, and bottom-right positions
corners = array[[0,0,-1,-1],[0,-1,0,-1]]

# Q2

In [5]:
# create a numpy array of shape (4,4) filled with random integers
array = np.random.randint(1,21, size=(4,4))
print(f"Original Array:\n {array}")

Original Array:
 [[17 17 17  4]
 [16 14  2  5]
 [11  1 18  1]
 [15  6  4 16]]


In [6]:
# use boolean indexing to set all elements greater than 10 to 10 
array[array>10]=10
print(f"Modified Array:\n{array}")

Modified Array:
[[10 10 10  4]
 [10 10  2  5]
 [10  1 10  1]
 [10  6  4 10]]
